[package]
org = "ballerina"
name = "data.jsondata"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["json", "json path", "json-transform", "json transform", "json to json", "json-convert", "json convert"]
repository = "https://github.com/ballerina-platform/module-ballerina-data.jsondata"
license = ["Apache-2.0"]
distribution = "2201.12.0"
export = ["data.jsondata"]

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "jsondata-native"
version = "@toml.version@"
path = "../native/build/libs/data.jsondata-native-@project.version@.jar"

[[platform.java21.dependency]]
path = "./lib/json-path-@jsonpath.version@.jar"
groupId = "com.jayway.jsonpath"
artifactId = "json-path"
version = "@jsonpath.version@"

[[platform.java21.dependency]]
path = "./lib/json-smart-@jsonsmart.version@.jar"
groupId = "net.minidev.json"
artifactId = "json-smart"
version = "@jsonsmart.version@"

[[platform.java21.dependency]]
path = "./lib/accessors-smart-@accessors.version@.jar"
groupId = "net.minidev.json"
artifactId = "accessors-smart"
version = "@accessors.version@"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "@constraint.version@"
path = "./lib/constraint-native-@stdlib.constraintnative.version@.jar"

[[platform.java21.dependency]]
path = "./lib/json-schema-validator-@networknt.json.schema.validator.version@.jar"
groupId = "com.networknt"
artifactId = "json-schema-validator"
version = "@networknt.json.schema.validator.version@"

[[platform.java21.dependency]]
path = "./lib/jackson-databind-@@jacksonDatabindVersion@@.jar"
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-databind"
version = "@@jacksonDatabindVersion@@"

[[platform.java21.dependency]]
path = "./lib/jackson-core-@@jacksonCoreVersion@@.jar"
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-core"
version = "@@jacksonCoreVersion@@"

[[platform.java21.dependency]]
path = "./lib/jackson-annotations-@@jacksonAnnotationsVersion@@.jar"
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-annotations"
version = "@@jacksonAnnotationsVersion@@"

[[platform.java21.dependency]]
path = "./lib/jackson-datatype-jsr310-@@jacksonDatatypeJsr310Version@@.jar"
groupId = "com.fasterxml.jackson.datatype"
artifactId = "jackson-datatype-jsr310"
version = "@@jacksonDatatypeJsr310Version@@"

[[platform.java21.dependency]]
path = "./lib/snakeyaml-@@snakeyamlVersion@@.jar"
groupId = "org.yaml"
artifactId = "snakeyaml"
version = "@@snakeyamlVersion@@"

[[platform.java21.dependency]]
path = "./lib/joni-@@joniVersion@@.jar"
groupId = "org.jruby.joni"
artifactId = "joni"
version = "@@joniVersion@@"

[[platform.java21.dependency]]
path = "./lib/jcodings-@@jcodingsVersion@@.jar"
groupId = "org.jruby.jcodings"
artifactId = "jcodings"
version = "@@jcodingsVersion@@"

