[package]
org = "ballerina"
name = "data.jsondata"
version = "1.1.4"
authors = ["Ballerina"]
keywords = ["json", "json path", "json-transform", "json transform", "json to json", "json-convert", "json convert"]
repository = "https://github.com/ballerina-platform/module-ballerina-data.jsondata"
license = ["Apache-2.0"]
distribution = "2201.12.0"
export = ["data.jsondata"]

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "jsondata-native"
version = "1.1.4"
path = "../native/build/libs/data.jsondata-native-1.1.4-SNAPSHOT.jar"

[[platform.java21.dependency]]
path = "./lib/json-path-2.9.0.jar"
groupId = "com.jayway.jsonpath"
artifactId = "json-path"
version = "2.9.0"

[[platform.java21.dependency]]
path = "./lib/json-smart-2.4.11.jar"
groupId = "net.minidev.json"
artifactId = "json-smart"
version = "2.4.11"

[[platform.java21.dependency]]
path = "./lib/accessors-smart-2.4.7.jar"
groupId = "net.minidev.json"
artifactId = "accessors-smart"
version = "2.4.7"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "1.7.0"
path = "./lib/constraint-native-1.7.0.jar"

[[platform.java21.dependency]]
path = "./lib/json-schema-validator-3.0.0.jar"
groupId = "com.networknt"
artifactId = "json-schema-validator"
version = "3.0.0"

#[[platform.java21.dependency]]
#path = "./lib/jackson-core-3.0.3.jar"
#groupId = "tools.jackson.core"
#artifactId = "jackson-core"
#version = "3.0.3"
#
#[[platform.java21.dependency]]
#path = "./lib/jackson-databind-3.0.3.jar"
#groupId = "tools.jackson.core"
#artifactId = "jackson-databind"
#version = "3.0.3"
#
#[[platform.java21.dependency]]
#path = "./lib/jackson-dataformat-yaml-3.0.3.jar"
#groupId = "tools.jackson.dataformat"
#artifactId = "jackson-dataformat-yaml"
#version = "3.0.3"
#
#[[platform.java21.dependency]]
#path = "./lib/jackson-annotations-2.20.jar"
#groupId = "com.fasterxml.jackson.core"
#artifactId = "jackson-annotations"
#version = "2.20"
#
#[[platform.java21.dependency]]
#path = "./lib/itu-1.14.0.jar"
#groupId = "com.ethlo.time"
#artifactId = "itu"
#version = "1.14.0"
#
#[[platform.java21.dependency]]
#path = "./lib/slf4j-api-2.0.17.jar"
#groupId = "org.slf4j"
#artifactId = "slf4j-api"
#version = "2.0.17"
#
#[[platform.java21.dependency]]
#path = "./lib/snakeyaml-engine-2.10.jar"
#groupId = "org.snakeyaml"
#artifactId = "snakeyaml-engine"
#version = "2.10"


